spring.application.name=09_SpringBoot_PropertiesFile

#Configuring the employee data
employeeId=AIT123
employeeName=Rajesh
designation=Senior Software Engineer
salary=35000
cityName=Chennai

#Configuring Customer Data
com.ashokit.customer.id=AIT3344
com.ashokit.customer.name=Suresh
com.ashokit.customer.billAmount=5000
com.ashokit.customer.address=Hyderabad
