#main application.properties

#Activating the current profile
spring.profiles.active=dev

#default profile configuration
database.username=default_username
database.password=default_password
application.emails=ashokit.default@gmail.com

#redis configuration
redis.username=redis_default
redis.password=redis_default