#prod Specific configuration
database.username=ashokit_prod
database.password=ashokit_prod
application.emails=ashokit.prod@gmail.com

#redis configuration
redis.username=redis_prod
redis.password=redis_prod