#Dev Specific configuration
database.username=ashokit_dev
database.password=ashokit_dev
application.emails=ashokit.dev@gmail.com

#redis configuration
redis.username=redis_dev
redis.password=redis_dev