#QA Specific configuration
database.username=ashokit_qa
database.password=ashokit_qa
application.emails=ashokit.qa@gmail.com

#redis configuration
redis.username=redis_qa
redis.password=redis_qa