#preprod Specific configuration
database.username=ashokit_preprod
database.password=ashokit_preprod
application.emails=ashokit.preprod@gmail.com

#redis configuration
redis.username=redis_preprod
redis.password=redis_preprod