spring.application.name=09_SpringBoot_PropertiesFile

#Configuring the employee data
com.ashokit.employee.id=10011
com.ashokit.employee.name=Suresh
com.ashokit.employee.salary=50000
com.ashokit.employee.location=Chennai
com.ashokit.employee.emailIds=mahesh1.ashokit@gmail.com, ashokit1@gmail.com